### ISSUE TITLE
MXF support

### ISSUE THREAD

**Issue by asaghri** [aws-solutions/video-on-demand-on-aws#124]
**Describe the feature you'd like**
Currently the .MXF source video file is not supported. Most of our files have this extension and I understand it's supported by mediaconvert.
So it would be definitely nice to have that feature !

**Comment by morjoan** [comment]
Hi there,
By default, the S3 event notification is configured to trigger the workflow when a video is uploaded with one of the following lowercase file extensions: .mp4, .mpg, .m4v, .m2ts, and .mov.

However, you can do one of the following options to include support for your file extension:

1. If you are comfortable rebuilding the solution, you may customize the S3 notification source code to include any file extensions supported by MediaConvert (like .MXF) to trigger the job: https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/custom-resource/lib/s3/index.js. After you make the changes, rebuild and redeploy the solution.
2. Edit your S3 source bucket's Event Notification to trigger on a .MXF (upper case) extension. See https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-event-notifications.html

Hope this gets you going!

**Comment by asaghri** [comment]
I've rebuilt the solution by adding the .mxf extension (lower case for me) and it works perfectly. 
Thank you for your help and let me know if you want me to add a pull request to cover these files.

**Comment by eggoynes** [comment]
Hi @asaghri. We added the .mxf file type as a feature on the 5.3.0 release. Thank you for your input.
