### ISSUE TITLE
CORS settings not included on /out/* distribution on CloudFront settings

### ISSUE THREAD

**Issue by vandevusse** [aws-solutions/video-on-demand-on-aws#127]
**Describe the bug**
Many customers were complaining that videos could not play or would freeze after starting.  We have spent a few weeks diagnosing this error and it corresponded with increased caching on our Cloudfront distribution, the more errors and complaints we were receiving.  This seemed really odd so we did some further digging.  We found the root cause of the issue - the CORS settings.  It turns out that by increasing the videos in our Cloudfront cache, by default, this was also caching the CORS headers themselves.  Therefore if the video that was playing had a segment that had been cached under the wrong origin, this would throw an error and depending on the device or browser being used, the video would potentially error or fail.

**To Reproduce**

1. Deploy the Cloudformation stack on a fresh environment
2. Check Cloudfront distribution settings on the destination stack
3. Check "out/*" on Behaviors
4. "Cache Based on Selected Request Headers" is set to None - we would expect this to be set to "Whitelist" with either Access-Control-Allow-Origin or Origin

**Expected behavior**
Videos played on different URLs or different devices should not fail with a CORS error.

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.0.0] - v5.2.0
- [ ] Region: [e.g. us-east-1] - us-easst-1
- [ ] Was the solution modified from the version published on this repository? - yes
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? - no
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? - no
- [ ] Were there any errors in the CloudWatch Logs? - no

**Screenshots**
<img width="924" alt="Screen Shot 2021-04-19 at 9 04 32 PM" src="https://user-images.githubusercontent.com/648305/115335834-d94ca080-a152-11eb-84bf-4dbe82e8b611.png">

**Comment by morjoan** [comment]
Hi,
Is the /out/* behavior a customization at your end? The default deployment of the solution only has one default behavior with these headers whitelisted: Origin, Access-Control-Request-Method, Access-Control-Request-Headers (as you can see here: https://github.com/awslabs/video-on-demand-on-aws/blob/master/deployment/video-on-demand-on-aws.yaml#L549).

**Comment by vandevusse** [comment]
@morjoan Thanks for taking a look at this. I believe it's deployed as part of the optional MediaPackage step. The code can be found at https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/custom-resource/lib/mediapackage/cloudfront.js#L56

**Comment by morjoan** [comment]
Ah right. Forgot about that optional part. We'll definitely take a closer look and fix as needed in our next release. Thanks for bringing it to our attention.

**Comment by vandevusse** [comment]
Thank you!

**Comment by Qoraiche** [comment]
Hi, any updates on this?

**Comment by rromanchuk** [comment]
If you're cross platform, including web, it's a bit more complicated, and extremely easy to regress, and even more painful to debug. 

I have multi-origin single distribution, that handles more than just the VOD, so I have forked this long ago, but the current default solution needs a lot of tweaks.   The origin/cache managed policies almost make this more complex, and thats on top of every developer just brute forcing their way with wild cards .  I swear, Cors + Cache is purgatory for developers. 

 I've had the best luck with the following. First, for anything video,  i only use the legacy cloudfront whitelist headers. It's way too easy to get lost/distracted with the managed policies.


<img width="803" alt="Screen Shot 2021-08-31 at 12 13 22 AM" src="https://user-images.githubusercontent.com/102188/131459303-bc3c3df0-9ed0-48a8-b645-441e0f7b41cb.png">

Browsers + modern video players explode if the following methods aren't allowed. Solution currently has `- AllowedMethods: [GET]`

<img width="474" alt="Screen Shot 2021-08-31 at 12 21 04 AM" src="https://user-images.githubusercontent.com/102188/131460581-8ed44099-a289-46cd-86ba-dc2519db8066.png">

Flip a coin on caching OPTIONS, no one knows. https://stackoverflow.com/questions/12358173/correct-s3-cloudfront-cors-configuration

I then do a little rain dance, and get ready to hand craft a JSON payload (upgraded from xml) and use the following cors for vod destination bucket. 

```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "Access-Control-Allow-Origin",
            "Access-Control-Request-Method",
            "Access-Control-Request-Headers",
            "ETag"
        ]
    }
]
```

**Comment by raulmlamzn** [comment]
Hello, I'd like to check if this issue is still valid before we close it. Is anyone still experiencing this issue in the current release?
