### ISSUE TITLE
Is mediaconvert good option for video editing?

### ISSUE THREAD

**Issue by shajayesh** [aws-solutions/video-on-demand-on-aws#130]
Mediaconvert is good for encoding, but we want something that can cut the video or merge the video. We know MC gives you that option, but looks expensive.
Is it better to build in house video edit software or chose other vendor?

**Comment by raulmlamzn** [comment]
Thanks for your comment. AWS Elemental MediaConvert supports both Input Stitching and Clipping (more info here: https://docs.aws.amazon.com/mediaconvert/latest/ug/assembling-multiple-inputs-and-input-clips.html).
