### ISSUE TITLE
Scaling down the resolution & preserving aspect ratio (1:1 and 9:16 formats)?

### ISSUE THREAD

**Issue by el-pol** [aws-solutions/video-on-demand-on-aws#133]
The template has a number of resolutions to encode, like `1920x1080`, `640x360`, etc. 

The problem is that I use videos that have aspect ratios of `4:3`, `1:1` or `9:16`.

Then with the template MediaConvert settings, the resulting files have black bars added to "match" these resolutions.

My question: is it possible to tell MediaConvert to "scale down" on the input resolution?

For example, if I have a 2000x2000 I want outputs that are: 1000x1000, 500x500, 200x200... And not 640x360 & 1920x1808 (because these are in a different aspect ratio which introduces black bars).

Thanks!

**Comment by morjoan** [comment]
Hi,  You can edit the templates provided by the solution and change the outputs that you'd rather use for your workflow. Instructions on how to do that are here: https://docs.aws.amazon.com/mediaconvert/latest/ug/modifying-job-templates.html

Also, MediaConvert has a feature called automated ABR that may be of interest to you. Please read up on it here: https://docs.aws.amazon.com/mediaconvert/latest/ug/auto-abr.html.  Please note that this is a PRO feature and I highly suggest you review the pricing for MediaConvert before trying it out.

**Comment by mritterfigma** [comment]
I spent some time looking at Automated ABR, but I could not get it to preserve my input video's aspect ratio (`1:1`). Instead, the ouputs are consistently `16:9`. Is it possible to preserve the input aspect ratio with Automated ABR?

**Comment by madhurmehta-sahi** [comment]
You can just define either width or height in the output job. Documentation does not define it clearly but I tried it on my own and it works perfectly. The service maintains the aspect ratio of the input file if you provide only one of the parameters(width or height)

**Comment by maiznadeem** [comment]
> You can just define either width or height in the output job. Documentation does not define it clearly but I tried it on my own and it works perfectly. The service maintains the aspect ratio of the input file if you provide only one of the parameters(width or height)

I tried this and it worked. Thanks man.
