### ISSUE TITLE
How does one alter the name of a job template and/or add new job templates?

### ISSUE THREAD

**Issue by llamacannon** [aws-solutions/video-on-demand-on-aws#135]
I have been searching and going back and forth with aws support and they don't know the answer so hopefully I'll have more luck here.

I see in the Lambda function ...-profiler it looks for the template and is seemingly where to tweak to have it look for higher resolution templates as well, but it's not hard coded for the template name or anything.  It references DynamoDB but from looking at DynamoDB it only has items for videos I've already created as opposed to a template.  I also have seen here in Github references to a Metadata file but I'm not sure where to find that.

What do I need to add or change such that new MediaConvert Job Templates and Job Templates with altered names will trigger when I upload a video?

Thanks

**Comment by morjoan** [comment]
Hi there,

The input-validate function is what determines what job template is to be used for the MediaConvert job depending on the resolution of your video input files. You could edit the values of the environment variables (eg. MediaConvert_Template_1080p ) in this function that point to the job templates to be used for the 2160, 1080, and/or 720 templates. 

When you first deploy the solution, you have the option to either trigger via video upload or metadata file (.json) upload. In cases where you want to use a specific job template for a job, the metadata file trigger can be the way to go.  The metadata file is something that you put together yourself. Metadata file information can be found here: https://docs.aws.amazon.com/solutions/latest/video-on-demand/appendix-e.html

Hope this gets you going!

**Comment by llamacannon** [comment]
Thanks, that does help clarify that aspect.  I do have it setup to trigger
on upload which I think is overall a nicer setup in the long run.

I checked out the input-validate function you mentioned.  It does seem to
be identifying the templates for each resolution but it's doing so via a
process object so I'm still not quite sure where to go to add in new
templates and/or change names of templates.  It seems like it may be that
it is supposed to just work automatically by having it analyse what job
templates are available and return the best fit, but I tried a new template
for 4k videos and it didn't work until I replaced an existing template with
the same 4k template, at which point it processed correctly.  Do I specify
the name of the job template anywhere, and if so where should I look for
that?

From the input-validate function -


            jobTemplate_2160p: process.env.MediaConvert_Template_2160p,
            jobTemplate_1080p: process.env.MediaConvert_Template_1080p,
            jobTemplate_720p: process.env.MediaConvert_Template_720p,

**Comment by llamacannon** [comment]
Hi,

Is the suggestion from the previous comment to essentially hardcode the
template name in instead of having it fetch the value?  I'll do that if I
have to but I'd prefer to understand where it's looking for the value (eg.
where does process.env.MediaConvert_Template_2160p look to get the actual
template name for that size).

**Comment by morjoan** [comment]
Hi,
My earlier suggestion was to go into the Lambda function itself and change the values of those environment variables: https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html

Those environment variables were initially set though the main CloudFormation template itself when you deployed the solution: https://github.com/awslabs/video-on-demand-on-aws/blob/master/deployment/video-on-demand-on-aws.yaml#L736
If you change those job template values in the CloudFormation template, you'll need rebuild the solution locally yourself and deploy the solution from your own S3 buckets. You'd be essentially creating a custom build: https://github.com/awslabs/video-on-demand-on-aws#creating-a-custom-build
