### ISSUE TITLE
One single video ends up without audio track

### ISSUE THREAD

**Issue by masinamichele** [aws-solutions/video-on-demand-on-aws#138]
**Describe the bug**
After successfully running 100+ videos through this system, I am left with a single one that keeps ending up without audio.
The input MP4 file is fine, with both a video track and an audio track.
The output file (DASH specifically, but it's the same with HLS) has no audio information.
The input file is generated the same way as the other videos. I even tried re-rendering it to avoid any potential rendering errors.

**To Reproduce**
* Upload a seemingly normal video file
* Wait for the workflow completed email
* Try the DASH output in any test player (I tried a few different ones, stuck with [THEOplayer](http://demo.theoplayer.com/test-for-ll-dash) because it gives me debug info)
* Notice no audio is present, and the player's debug info show no data about the audio track.

**Expected behavior**
The video should have audio, like every other one.

**Please complete the following information about the solution:**
- [ ] Version: 5.2.0
- [ ] Region: eu-west-1
- [ ] Was the solution modified from the version published on this repository? Yes, I added encryption in MediaPackage, in two new dedicated packaging configurations (DASH and HLS), but I'm trying the default, unencrypted, DASH stream
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes, no quota reached. Also, I ran other videos after this one and they work correctly.
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**

THEOplayer debug info:
![Schermata 2021-11-17 alle 12 30 11](https://user-images.githubusercontent.com/1498413/142192765-2d9a58d4-8e0e-496a-b96a-1c8eb35d0070.png)

<details>
<summary>MediaInfo output of problematic file</summary>
<table width="100%" border="0" cellpadding="1" cellspacing="2" style="border:1px solid Navy">
<tr>
    <td width="150"><h2>General</h2></td>
  </tr>
  <tr>
    <td><i>Complete name :</i></td>
    <td colspan="3">/Volumes/GoogleDrive/Drive condivisi/Tootor - Contenuti/ASO/ASO normale/16-11-21 Aggiornamento video/SS_01_ASO/SS_01_ASO_Completo_v4.mp4</td>
  </tr>
  <tr>
    <td><i>Format :</i></td>
    <td colspan="3">MPEG-4</td>
  </tr>
  <tr>
    <td><i>Format profile :</i></td>
    <td colspan="3">Base Media / Version 2</td>
  </tr>
  <tr>
    <td><i>Codec ID :</i></td>
    <td colspan="3">mp42 (mp42/mp41)</td>
  </tr>
  <tr>
    <td><i>File size :</i></td>
    <td colspan="3">560 MiB</td>
  </tr>
  <tr>
    <td><i>Duration :</i></td>
    <td colspan="3">7 min 48 s</td>
  </tr>
  <tr>
    <td><i>Overall bit rate mode :</i></td>
    <td colspan="3">Variable</td>
  </tr>
  <tr>
    <td><i>Overall bit rate :</i></td>
    <td colspan="3">10.0 Mb/s</td>
  </tr>
  <tr>
    <td><i>Encoded date :</i></td>
    <td colspan="3">UTC 2021-11-17 09:46:53</td>
  </tr>
  <tr>
    <td><i>Tagged date :</i></td>
    <td colspan="3">UTC 2021-11-17 09:47:12</td>
  </tr>
  <tr>
    <td><i>TIM :</i></td>
    <td colspan="3">00:00:00:00</td>
  </tr>
  <tr>
    <td><i>TSC :</i></td>
    <td colspan="3">30000</td>
  </tr>
  <tr>
    <td><i>TSZ :</i></td>
    <td colspan="3">1001</td>
  </tr>
</table>
<br />
<table width="100%" border="0" cellpadding="1" cellspacing="2" style="border:1px solid Navy">
<tr>
    <td width="150"><h2>Video</h2></td>
  </tr>
  <tr>
    <td><i>ID :</i></td>
    <td colspan="3">1</td>
  </tr>
  <tr>
    <td><i>Format :</i></td>
    <td colspan="3">AVC</td>
  </tr>
  <tr>
    <td><i>Format/Info :</i></td>
    <td colspan="3">Advanced Video Codec</td>
  </tr>
  <tr>
    <td><i>Format profile :</i></td>
    <td colspan="3">Main@L4.1</td>
  </tr>
  <tr>
    <td><i>Format settings :</i></td>
    <td colspan="3">CABAC / 3 Ref Frames</td>
  </tr>
  <tr>
    <td><i>Format settings, CABAC :</i></td>
    <td colspan="3">Yes</td>
  </tr>
  <tr>
    <td><i>Format settings, Reference frames :</i></td>
    <td colspan="3">3 frames</td>
  </tr>
  <tr>
    <td><i>Format settings, GOP :</i></td>
    <td colspan="3">M=1, N=30</td>
  </tr>
  <tr>
    <td><i>Codec ID :</i></td>
    <td colspan="3">avc1</td>
  </tr>
  <tr>
    <td><i>Codec ID/Info :</i></td>
    <td colspan="3">Advanced Video Coding</td>
  </tr>
  <tr>
    <td><i>Duration :</i></td>
    <td colspan="3">7 min 48 s</td>
  </tr>
  <tr>
    <td><i>Source duration :</i></td>
    <td colspan="3">7 min 48 s</td>
  </tr>
  <tr>
    <td><i>Bit rate :</i></td>
    <td colspan="3">9 715 kb/s</td>
  </tr>
  <tr>
    <td><i>Width :</i></td>
    <td colspan="3">1 920 pixels</td>
  </tr>
  <tr>
    <td><i>Height :</i></td>
    <td colspan="3">1 080 pixels</td>
  </tr>
  <tr>
    <td><i>Display aspect ratio :</i></td>
    <td colspan="3">16:9</td>
  </tr>
  <tr>
    <td><i>Frame rate mode :</i></td>
    <td colspan="3">Constant</td>
  </tr>
  <tr>
    <td><i>Frame rate :</i></td>
    <td colspan="3">29.970 (30000/1001) FPS</td>
  </tr>
  <tr>
    <td><i>Color space :</i></td>
    <td colspan="3">YUV</td>
  </tr>
  <tr>
    <td><i>Chroma subsampling :</i></td>
    <td colspan="3">4:2:0</td>
  </tr>
  <tr>
    <td><i>Bit depth :</i></td>
    <td colspan="3">8 bits</td>
  </tr>
  <tr>
    <td><i>Scan type :</i></td>
    <td colspan="3">Progressive</td>
  </tr>
  <tr>
    <td><i>Bits/(Pixel*Frame) :</i></td>
    <td colspan="3">0.156</td>
  </tr>
  <tr>
    <td><i>Stream size :</i></td>
    <td colspan="3">542 MiB (97%)</td>
  </tr>
  <tr>
    <td><i>Source stream size :</i></td>
    <td colspan="3">542 MiB (97%)</td>
  </tr>
  <tr>
    <td><i>Language :</i></td>
    <td colspan="3">English</td>
  </tr>
  <tr>
    <td><i>Encoded date :</i></td>
    <td colspan="3">UTC 2021-11-17 09:46:53</td>
  </tr>
  <tr>
    <td><i>Tagged date :</i></td>
    <td colspan="3">UTC 2021-11-17 09:46:53</td>
  </tr>
  <tr>
    <td><i>Codec configuration box :</i></td>
    <td colspan="3">avcC</td>
  </tr>
</table>
<br />
<table width="100%" border="0" cellpadding="1" cellspacing="2" style="border:1px solid Navy">
<tr>
    <td width="150"><h2>Audio</h2></td>
  </tr>
  <tr>
    <td><i>ID :</i></td>
    <td colspan="3">2</td>
  </tr>
  <tr>
    <td><i>Format :</i></td>
    <td colspan="3">AAC LC</td>
  </tr>
  <tr>
    <td><i>Format/Info :</i></td>
    <td colspan="3">Advanced Audio Codec Low Complexity</td>
  </tr>
  <tr>
    <td><i>Codec ID :</i></td>
    <td colspan="3">mp4a-40-2</td>
  </tr>
  <tr>
    <td><i>Duration :</i></td>
    <td colspan="3">7 min 48 s</td>
  </tr>
  <tr>
    <td><i>Source duration :</i></td>
    <td colspan="3">7 min 48 s</td>
  </tr>
  <tr>
    <td><i>Bit rate mode :</i></td>
    <td colspan="3">Variable</td>
  </tr>
  <tr>
    <td><i>Bit rate :</i></td>
    <td colspan="3">317 kb/s</td>
  </tr>
  <tr>
    <td><i>Maximum bit rate :</i></td>
    <td colspan="3">492 kb/s</td>
  </tr>
  <tr>
    <td><i>Channel(s) :</i></td>
    <td colspan="3">2 channels</td>
  </tr>
  <tr>
    <td><i>Channel layout :</i></td>
    <td colspan="3">L R</td>
  </tr>
  <tr>
    <td><i>Sampling rate :</i></td>
    <td colspan="3">48.0 kHz</td>
  </tr>
  <tr>
    <td><i>Frame rate :</i></td>
    <td colspan="3">46.875 FPS (1024 SPF)</td>
  </tr>
  <tr>
    <td><i>Compression mode :</i></td>
    <td colspan="3">Lossy</td>
  </tr>
  <tr>
    <td><i>Stream size :</i></td>
    <td colspan="3">17.7 MiB (3%)</td>
  </tr>
  <tr>
    <td><i>Source stream size :</i></td>
    <td colspan="3">17.7 MiB (3%)</td>
  </tr>
  <tr>
    <td><i>Language :</i></td>
    <td colspan="3">English</td>
  </tr>
  <tr>
    <td><i>Encoded date :</i></td>
    <td colspan="3">UTC 2021-11-17 09:46:53</td>
  </tr>
  <tr>
    <td><i>Tagged date :</i></td>
    <td colspan="3">UTC 2021-11-17 09:46:53</td>
  </tr>
</table>
</details>

<details>
<summary>MediaInfo output of a working file</summary>
<table width="100%" border="0" cellpadding="1" cellspacing="2" style="border:1px solid Navy">
<tr>
    <td width="150"><h2>General</h2></td>
  </tr>
  <tr>
    <td><i>Complete name :</i></td>
    <td colspan="3">/Volumes/GoogleDrive/Drive condivisi/Tootor - Contenuti/Odontoiatri/Ottobre 2021/04-10-21 Aggiornamento video /VA_02/VA_02_Completo.mp4</td>
  </tr>
  <tr>
    <td><i>Format :</i></td>
    <td colspan="3">MPEG-4</td>
  </tr>
  <tr>
    <td><i>Format profile :</i></td>
    <td colspan="3">Base Media / Version 2</td>
  </tr>
  <tr>
    <td><i>Codec ID :</i></td>
    <td colspan="3">mp42 (mp42/mp41)</td>
  </tr>
  <tr>
    <td><i>File size :</i></td>
    <td colspan="3">873 MiB</td>
  </tr>
  <tr>
    <td><i>Duration :</i></td>
    <td colspan="3">11 min 46 s</td>
  </tr>
  <tr>
    <td><i>Overall bit rate mode :</i></td>
    <td colspan="3">Variable</td>
  </tr>
  <tr>
    <td><i>Overall bit rate :</i></td>
    <td colspan="3">10.4 Mb/s</td>
  </tr>
  <tr>
    <td><i>Encoded date :</i></td>
    <td colspan="3">UTC 2021-07-16 17:02:22</td>
  </tr>
  <tr>
    <td><i>Tagged date :</i></td>
    <td colspan="3">UTC 2021-07-16 17:02:51</td>
  </tr>
  <tr>
    <td><i>TIM :</i></td>
    <td colspan="3">00:00:00:00</td>
  </tr>
  <tr>
    <td><i>TSC :</i></td>
    <td colspan="3">30000</td>
  </tr>
  <tr>
    <td><i>TSZ :</i></td>
    <td colspan="3">1001</td>
  </tr>
</table>
<br />
<table width="100%" border="0" cellpadding="1" cellspacing="2" style="border:1px solid Navy">
<tr>
    <td width="150"><h2>Video</h2></td>
  </tr>
  <tr>
    <td><i>ID :</i></td>
    <td colspan="3">1</td>
  </tr>
  <tr>
    <td><i>Format :</i></td>
    <td colspan="3">AVC</td>
  </tr>
  <tr>
    <td><i>Format/Info :</i></td>
    <td colspan="3">Advanced Video Codec</td>
  </tr>
  <tr>
    <td><i>Format profile :</i></td>
    <td colspan="3">Main@L4.1</td>
  </tr>
  <tr>
    <td><i>Format settings :</i></td>
    <td colspan="3">CABAC / 3 Ref Frames</td>
  </tr>
  <tr>
    <td><i>Format settings, CABAC :</i></td>
    <td colspan="3">Yes</td>
  </tr>
  <tr>
    <td><i>Format settings, Reference frames :</i></td>
    <td colspan="3">3 frames</td>
  </tr>
  <tr>
    <td><i>Format settings, GOP :</i></td>
    <td colspan="3">M=1, N=30</td>
  </tr>
  <tr>
    <td><i>Codec ID :</i></td>
    <td colspan="3">avc1</td>
  </tr>
  <tr>
    <td><i>Codec ID/Info :</i></td>
    <td colspan="3">Advanced Video Coding</td>
  </tr>
  <tr>
    <td><i>Duration :</i></td>
    <td colspan="3">11 min 46 s</td>
  </tr>
  <tr>
    <td><i>Bit rate :</i></td>
    <td colspan="3">10.0 Mb/s</td>
  </tr>
  <tr>
    <td><i>Width :</i></td>
    <td colspan="3">1 920 pixels</td>
  </tr>
  <tr>
    <td><i>Height :</i></td>
    <td colspan="3">1 080 pixels</td>
  </tr>
  <tr>
    <td><i>Display aspect ratio :</i></td>
    <td colspan="3">16:9</td>
  </tr>
  <tr>
    <td><i>Frame rate mode :</i></td>
    <td colspan="3">Constant</td>
  </tr>
  <tr>
    <td><i>Frame rate :</i></td>
    <td colspan="3">29.970 (30000/1001) FPS</td>
  </tr>
  <tr>
    <td><i>Color space :</i></td>
    <td colspan="3">YUV</td>
  </tr>
  <tr>
    <td><i>Chroma subsampling :</i></td>
    <td colspan="3">4:2:0</td>
  </tr>
  <tr>
    <td><i>Bit depth :</i></td>
    <td colspan="3">8 bits</td>
  </tr>
  <tr>
    <td><i>Scan type :</i></td>
    <td colspan="3">Progressive</td>
  </tr>
  <tr>
    <td><i>Bits/(Pixel*Frame) :</i></td>
    <td colspan="3">0.161</td>
  </tr>
  <tr>
    <td><i>Stream size :</i></td>
    <td colspan="3">845 MiB (97%)</td>
  </tr>
  <tr>
    <td><i>Language :</i></td>
    <td colspan="3">English</td>
  </tr>
  <tr>
    <td><i>Encoded date :</i></td>
    <td colspan="3">UTC 2021-07-16 17:02:22</td>
  </tr>
  <tr>
    <td><i>Tagged date :</i></td>
    <td colspan="3">UTC 2021-07-16 17:02:22</td>
  </tr>
  <tr>
    <td><i>Codec configuration box :</i></td>
    <td colspan="3">avcC</td>
  </tr>
</table>
<br />
<table width="100%" border="0" cellpadding="1" cellspacing="2" style="border:1px solid Navy">
<tr>
    <td width="150"><h2>Audio</h2></td>
  </tr>
  <tr>
    <td><i>ID :</i></td>
    <td colspan="3">2</td>
  </tr>
  <tr>
    <td><i>Format :</i></td>
    <td colspan="3">AAC LC</td>
  </tr>
  <tr>
    <td><i>Format/Info :</i></td>
    <td colspan="3">Advanced Audio Codec Low Complexity</td>
  </tr>
  <tr>
    <td><i>Codec ID :</i></td>
    <td colspan="3">mp4a-40-2</td>
  </tr>
  <tr>
    <td><i>Duration :</i></td>
    <td colspan="3">11 min 46 s</td>
  </tr>
  <tr>
    <td><i>Source duration :</i></td>
    <td colspan="3">11 min 46 s</td>
  </tr>
  <tr>
    <td><i>Bit rate mode :</i></td>
    <td colspan="3">Variable</td>
  </tr>
  <tr>
    <td><i>Bit rate :</i></td>
    <td colspan="3">317 kb/s</td>
  </tr>
  <tr>
    <td><i>Maximum bit rate :</i></td>
    <td colspan="3">403 kb/s</td>
  </tr>
  <tr>
    <td><i>Channel(s) :</i></td>
    <td colspan="3">2 channels</td>
  </tr>
  <tr>
    <td><i>Channel layout :</i></td>
    <td colspan="3">L R</td>
  </tr>
  <tr>
    <td><i>Sampling rate :</i></td>
    <td colspan="3">48.0 kHz</td>
  </tr>
  <tr>
    <td><i>Frame rate :</i></td>
    <td colspan="3">46.875 FPS (1024 SPF)</td>
  </tr>
  <tr>
    <td><i>Compression mode :</i></td>
    <td colspan="3">Lossy</td>
  </tr>
  <tr>
    <td><i>Stream size :</i></td>
    <td colspan="3">26.7 MiB (3%)</td>
  </tr>
  <tr>
    <td><i>Source stream size :</i></td>
    <td colspan="3">26.7 MiB (3%)</td>
  </tr>
  <tr>
    <td><i>Language :</i></td>
    <td colspan="3">English</td>
  </tr>
  <tr>
    <td><i>Encoded date :</i></td>
    <td colspan="3">UTC 2021-07-16 17:02:22</td>
  </tr>
  <tr>
    <td><i>Tagged date :</i></td>
    <td colspan="3">UTC 2021-07-16 17:02:22</td>
  </tr>
</table>
</details>

**Additional context**
I cannot publicly provide the video file and the DASH url as it is copyrighted content. I will happily provide both privately if needed.

Thank you for any help.

**Comment by masinamichele** [comment]
I tried deleting and re-creating the MediaConvert job template (stack-name_Ott_1080p_Avc_Aac_16x9_mvod_no_preset), just in case I misconfigured something.

I tried with the same mysterious video and another working one (different from the one described in the first message), and nothing changed, the working one continued working as before, and the other one still completed without audio.

Both videos triggered the job using the same template.

I tried contacting our video supplier, who told me that video was exported in the same way the other were exported.
He gave me a few different versions of the same video (I don't know what he did between every version), but all of them behave the same.

As of now, I have no idea what to tell them, not even a clue at what to look out for. I'm pretty sure it has to be something on their part (i.e. not mine of AWS's fault), but I can't seem to find anything strange about that video.

**Comment by masinamichele** [comment]
I tried diff-ing two MediaInfo outputs, one for the bad video, and the other for a working one.

Here is the diff output, from which I removed the common fields and the obvious differences (like filename, duration, size and dates):

(negative is the bad one, positive is the good one)
```diff
General
- Overall bit rate: 10.0 Mb/s
+ Overall bit rate: 9 809 kb/s

Video
- Source duration: 7 min 48 s
+
- Bit rate: 9 715 kb/s
+ Bit rate: 9 479 kb/s
- Bits/(Pixel*Frame): 0.156
+ Bits/(Pixel*Frame): 0.153
- Source stream size: 542 MiB (97%)
+

Audio
- Maximum bit rate: 492 kb/s
+ Maximum bit rate: 447 kb/s
```

Besides what I feel are normal differences (like bitrate), the only thing is that the bad one has the video duration and video stream size paired with their "Source" counterpart.

**Comment by eggoynes** [comment]
Hi @masinamichele

Thank you for filing this issue.  I can take a look and see why the audio is not making it through. My email is my GitHub alias at amazon.com. If you sent the link there.

The  Mediainfo info looks fine. I would have to see the video to do deeper analysis. 

Thank you.

**Comment by Higherings** [comment]
Hello, @eggoynes I have the exact same issue, processed more than 250 videos and two of them have no Audio, I even try to reprocess the mp4 output from the template (that does have audio) but it is the same result, video without audio.
Tell me if can send you a sample of videos that I ran, the one that fail and the one that works. I don't want to spam you.

**Comment by eggoynes** [comment]
Hello @Higherings no worries. You can send me a link to your video as well on email. I will inspect it and see what is causing the audio to not make it to your output files. Thanks

**Comment by masinamichele** [comment]
Hello @eggoynes 
As requested, I've sent you an email with the file and the DASH url.

Thank you.

**Comment by eggoynes** [comment]
Hello @masinamichele and @Higherings I got both of your videos earlier today. 

I processed the videos through the new V5.3.0 version of this solution that was released yesterday. Good news, I heard audio on both files when I played them back using the HLS stream. The update may have fixed it. 

Let me know if that works, and if you have any further questions. 
https://github.com/aws-solutions/video-on-demand-on-aws/releases/tag/v5.3.0

I hope that helps. 

**Quick overview of the 5.3.0 update**
Part of this update was lowering costs by turning off features that cause AWS MediaConvert to run in Pro Tier, such as the de-interlacer. This allows AWS MediaConvert to run in Basic Tier mode to save money. We also had a survey that most customers were using the HLS output, so we saved over 60% of the cost by having the default template output HLS. 


The next update I am working on has an improved mechanism for switching between different AWS MediaConvert templates. We also want to have a list of sample AWS MediaConvert json templates with a simple way to switch between them very easily. Let me know if that sounds interesting. 

Thanks

**Comment by Higherings** [comment]
Thanks @eggoynes, I will try the update on our Staging Env and then pass it to Prod Env (where the issue is), I will update as soon as possible.
The work you are doing sounds great!

**Comment by eggoynes** [comment]
Marking as resolved. Please reopen if you have trouble. Thanks

**Comment by Higherings** [comment]
Hello @eggoynes I just finished the update to 5.3.0 but still the same video has no audio. Do you think there is something else to check?

**Comment by eggoynes** [comment]
@Higherings Awesome. Glad to hear it did the trick.
