### ISSUE TITLE
Unable to update the stack to the recent available

### ISSUE THREAD

**Issue by mzahidriaz** [aws-solutions/video-on-demand-on-aws#146]
**Describe the bug**
Unable to update the stack to the recent available

**Expected behavior**
Should be able to update the stack without any issues

**Please complete the following information about the solution:**
- [ ] Region: us-west-2
- [ ] Was the solution modified from the version published on this repository?: No

**Screenshots**
![image](https://user-images.githubusercontent.com/2793322/165702545-b2befde2-23f7-4f6e-9519-11be3975eebf.png)

**Additional context**
Wanted to update the stack to the latest version available, but not able to do so because of the issue mentioned in the screenshot.

**Comment by raulmlamzn** [comment]
Thanks for your feedback @mzahidriaz. Can you please confirm if you were able to update the stack or still an issue for you?

**Comment by mzahidriaz** [comment]
@raulmlamzn No I was not able to update

**Comment by raulmlamzn** [comment]
Can you please confirm the version that you are running?

**Comment by raulmlamzn** [comment]
Closing this ticket, but please respond with more details if you are still having issues or create new ticket

**Comment by mzahidriaz** [comment]
![image](https://github.com/aws-solutions/video-on-demand-on-aws/assets/2793322/00ddd034-a44c-4751-ab58-483bd7ead70b)
Here is the error screenshot. 
I tried again to update the stack
