### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by zhu** [aws-solutions/video-on-demand-on-aws#153]
https://github.com/aws-solutions/video-on-demand-on-aws/blob/ff9b31a20edc833532ab16e82f283db6e38858b9/source/output-validate/index.js#L119
`legnth` should be `length` ?

**Comment by cassneal** [comment]
Hi @zhu we have added this issue to our solution's backlog. Thank you for filing. Please let us know if this typo has caused any functionality to not work correctly for you.

**Comment by raulmlamzn** [comment]
Added to the backlog

**Comment by eggoynes** [comment]
Hi @zhu 

We fixed it in this release. Thanks.

https://github.com/aws-solutions/video-on-demand-on-aws/releases/tag/v6.1.4
