### ISSUE TITLE
appRegistry associateStack has been deprecated

### ISSUE THREAD

**Issue by Dev-Destructor** [aws-solutions/video-on-demand-on-aws#155]
`const appRegistry = new appreg.Application(this, 'AppRegistryApp', {
      applicationName: applicationName,
      description: `Service Catalog application to track and manage all your resources. The SolutionId is ${solutionId} and SolutionVersion is %%VERSION%%.`
    });
    appRegistry.associateStack(this);
    cdk.Tags.of(appRegistry).add('solutionId', solutionId);
    cdk.Tags.of(appRegistry).add('SolutionName', solutionName);
    cdk.Tags.of(appRegistry).add('SolutionDomain', 'CloudFoundations');
    cdk.Tags.of(appRegistry).add('SolutionVersion', '%%VERSION%%');
    cdk.Tags.of(appRegistry).add('ApplicationType', 'AWS-Solutions');

    appRegistry.node.addDependency(attributeGroup);
    appRegistry.associateAttributeGroup(attributeGroup);`

**Comment by cassneal** [comment]
@Dev-Destructor  can you elaborate more on this issue? what is the expected behavior? what are the steps you are taking to get to this current issue?

**Comment by Dev-Destructor** [comment]
"associateStack" method of the Application function under "@aws-cdk/aws-servicecatalogappregistry-alpha" has been deprecated. I had to change with "associateApplicationWithStack".

**Comment by cassneal** [comment]
Thanks. We will review this shortly.

**Comment by cassneal** [comment]
This will be fixed in our next release. Will update this issue once we have deployed. Thank you

**Comment by cassneal** [comment]
This has been fixed in 6.1.0 that was released yesterday.
