### ISSUE TITLE
error while trying to build using codebuild + buildspec.yml

### ISSUE THREAD

**Issue by aro1976** [aws-solutions/video-on-demand-on-aws#159]
**Describe the bug**
Trying to build the solution by using CodeBuild, but it seems there is a script that is missing from the repository build-open-source-dist.sh

**To Reproduce**
Create a CodeBuild project getting the source from current repository and start build using buildspec on project source repository.

**Expected behavior**
Deploy solution to S3 Bucket

**Please complete the following information about the solution:**
- [main] Version: [e.g. v1.0.0]
- [us-east-1] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [yes] If the answer to the previous question was yes, are the changes available on GitHub?
- [no] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [yes] Were there any errors in the CloudWatch Logs?

Build Logs
```
980 | [Container] 2023/03/16 00:20:55 Running command echo "Starting open-source-dist `date` in `pwd`"
981 | Starting open-source-dist Thu Mar 16 00:20:55 UTC 2023 in /codebuild/output/src076791728/src/github.com/clouddog-br/video-on-demand-on-aws/deployment
982 |  
983 | [Container] 2023/03/16 00:20:55 Running command chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh $SOLUTION_NAME
984 | chmod: cannot access './build-open-source-dist.sh': No such file or directory
985 |  
986 | [Container] 2023/03/16 00:20:55 Command did not exit successfully chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh $SOLUTION_NAME exit status 1
987 | [Container] 2023/03/16 00:20:55 Phase complete: BUILD State: FAILED
988 | [Container] 2023/03/16 00:20:55 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh $SOLUTION_NAME. Reason: exit status 1
989 | [Container] 2023/03/16 00:20:55 Entering phase POST_BUILD
990 | [Container] 2023/03/16 00:20:55 Running command echo "Retrieving next stage buildspec `date` in `pwd`"
991 | Retrieving next stage buildspec Thu Mar 16 00:20:55 UTC 2023 in /codebuild/output/src076791728/src/github.com/clouddog-br/video-on-demand-on-aws/deployment
992

```

**Comment by raulmlamzn** [comment]
Thanks for your feedback. We are currently reviewing this with our engineering team.

**Comment by raulmlamzn** [comment]
Hello @aro1976, please follow these guidelines to deploy the solution instead: https://docs.aws.amazon.com/solutions/latest/video-on-demand/deployment.html
