### ISSUE TITLE
<Error><Code>SignatureDoesNotMatch</Code><Message>

### ISSUE THREAD

**Issue by danestves** [aws-solutions/video-on-demand-on-aws#168]
**Describe the bug**

Getting `<Error><Code>SignatureDoesNotMatch</Code><Message>` and `TypeError: 'NoneType' object is not subscriptable Traceback`

**To Reproduce**

Install the latest version of the stack

**Expected behavior**

Process the media info lambda

**Please complete the following information about the solution:**

- [x] Version: v6.1.2
- [x] Region: us-east-2
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? Bi
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? Yes

**Screenshots**

![](https://user-images.githubusercontent.com/31737273/236584906-712932b6-5c16-44e1-9771-664bc373c434.png)

**Additional context**

N/A

**Comment by danestves** [comment]
After I make a little debug, it happens with a few videos but not with all

**Comment by cassneal** [comment]
Anything unique about the ones where you receive the error?

**Comment by danestves** [comment]
> Anything unique about the ones where you receive the error?

I saw that was because when trying to request the source in CloudFront after a few milliseconds that was created, sometimes it gives a 404 that doesn't found the source. After I add more retries to the steps functions, works like a charm

**Comment by colin-oos** [comment]
I am having this exact issue occur 100% of the time with all my videos I upload. However, this is only happening for me with one of my stacks that I deployed today. My other deployments / applications are running just fine using the same stack version 6.1.0 and there is nothing different about them other than they have different stack names. They are deployed in us-east-2

**Comment by colin-oos** [comment]
@danestves Adding more retries worked for me too. I changed from 6 to 12. While this is a nice workaround, I am still uneasy. How come this only happens on one of my stacks and does this mean every time I launch a new one I will have to increase the step retries? I launch a stack for every new tenant, so I could see this getting tedious. Perhaps a PR could be made.

**Comment by dch90** [comment]
With the release of Video on Demand on AWS `v6.1.3`, this issue is now resolved.
Thank you for everyone's feedback.
