### ISSUE TITLE
How can I encrypt my data with AWS mediapackage (quesiton)

### ISSUE THREAD

**Issue by sailawhk** [aws-solutions/video-on-demand-on-aws#198]
Hello,

Is is possible to use  drm in mediapackage?
As I saw most of them apply it in mediaconvert

Thanks
CK

**Comment by raulmlamzn** [comment]
Hello CK, 
Yes AWS Elemental MediaPackage supports DRM and uses the AWS Secure Packager and Encoder Key Exchange (SPEKE) API. Here's some info with a list of Amazon partners that support SPEKE:
https://docs.aws.amazon.com/mediapackage/latest/ug/using-encryption.html
https://docs.aws.amazon.com/speke/latest/documentation/customer-onboarding.html#choose-drm-provider

**Comment by sailawhk** [comment]
Hello Raulmlamzn,

Yes I will try SPEKE from the provider. Still trouble the problem.
I'm using the vod solution and setting the DRM in mediapackage video on demond, package group, package configuration.
Seems it doesn't work. I follow the SPEKE provider to set the API to check the connection, it should be work.

Thanks
CK
