### ISSUE TITLE
With CDKv2 failed to deploy

### ISSUE THREAD

**Issue by rahulkumar96t** [aws-solutions/video-on-demand-on-aws#218]
I am trying to deploy this solution with cdk v2, but it is failing to deploy 

19:59:15 | CREATE_FAILED        | AWS::CloudFormation::CustomResource                       | UUID/Default
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [********]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation
can attach the updated version.

This happens with the CustomResource. I was trying with node 18, node 20 and node 16, but with non of them it worked. When i am using CloudFormation template it is working. But, i need to deploy using cdk.

**Comment by stankowalik** [comment]
Hi ;) I also find the deployment process described in Readme quite confusing. But to just deploy it with CDK I think the trick was to make sure that all the dependencies are installed in the subfolders. From what I remember missing dependencies in node_module in each subfolder in source are causing "CloudFormation did not receive a response from your Custom Resource". To do that make sure your _npm install_ command on root jumps to each subfolder in source and runs npm install. You can also try to run tests - that should install all the dependencies as the pretest installs dependencies ;)

**Comment by rahulkumar96t** [comment]
Thanks @stankowalik for helping working now.
