### ISSUE TITLE
convert question how to keep  video conversion

### ISSUE THREAD

**Issue by lgb861213** [aws-solutions/video-on-demand-on-aws#244]
How to ensure the output of video conversion is adaptively scaled while hard setting 16X9

**Comment by raulmlamzn** [comment]
Thanks for your question @lgb861213. You can control how to scale you video input to the output by using the setting Scaling behavior in AWS Elemental MediaConvert. The default setting is "Fit with padding". 
Please review the Video Scaling section in the MediaConvert User guide: https://docs.aws.amazon.com/mediaconvert/latest/ug/video-scaling.html

**Comment by raulmlamzn** [comment]
Feel free to re-open with an update or additional questions
