### ISSUE TITLE
Make the CloudFormation stack workable in China region

### ISSUE THREAD

**Issue by liangruibupt** [aws-solutions/video-on-demand-on-aws#41]
I create a CloudFormation stack template workable in China region
https://github.com/liangruibupt/video-on-demand-on-aws-cn

I have tested it in AWS NingXia Region. 
Maybe you can help review it and merge into the master branch

**Comment by dscpinheiro** [comment]
Hi @liangruibupt, 

We've taken a look at your feature request and have added it to our backlog for upcoming versions of the solution. 

Thanks!
