### ISSUE TITLE
How to sign MediaPackage/Cloudfront URLs?

### ISSUE THREAD

**Issue by numToStr** [aws-solutions/video-on-demand-on-aws#94]
**Is your feature request related to a problem? Please describe.**

I am using the MediaPackage flow and I want to sign the generated media package URL using Cloudfont Signed URLs. I already created the CloudFront keys and updated my distribution with the self as a trusted signer. But I am kinda lost when It comes to editing the source code to created the signed URLs. It would be a great help If anyone can guide me on which file to edit.

**Comment by tomnight** [comment]
The output validate step in the publishing workflow is the step that will generate the CloudFront URLS this is a lambda function so you will need to update this to generate the signed URLs.

https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/output-validate/index.js

There's a good example here on how to generate URLs:

https://aws.amazon.com/blogs/developer/creating-amazon-cloudfront-signed-urls-in-node-js/

hope this helps

**Comment by numToStr** [comment]
So, I don't need to edit anything in the https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/media-package-assets/index.js as I'll be using the media package output URLS??

**Comment by realvikas** [comment]
Hi, @tomnight I am stuck with the same. Can you guide us?

**Comment by tomnight** [comment]
Hi Sorry for the delay,

The mediapackage-assets lambda function creates the URLs for the mediapackage endpoints, so yes you would need to update this to convert the URLS to signed URLS. 

The only difference I would make to the example I gave above is I would recommend that you store the private key in secrets manager and the function to:
* get the private key.
* generate the signed URLS.
* update the egressEndpoints object in the data returned by the function with the signed URLs
